name: Pages Deploy

on:
  workflow_run:
    workflows:
      - 'Test Workflow'
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write # Добавляем это разрешение для использования OIDC

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: . # Указываем корень проекта, где находится index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
